name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install ldid
       run: |
        curl -o ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
        chmod +x ldid
     - name: Build App
       run: make all
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            for IPA in *.ipa; do
            git add "$IPA"
            done
            git commit -m "Built App"
            git push
